### ISSUE TITLE
Fire Rate

### ISSUE THREAD

**Issue by tuirgin** [michalzc/oq-system#125]
The Fire Rate takes a number, which means the common nomenclature for Rate cannot be used; i.e. 1/2 or 1/3 for slower weapons have to be represented by 0.5 and 0.3.

- If no mechanization is intended, a simple text field would solve the problem.
- If there's an intention of tracking rate of fire, better would be a combo menu with an itemization of all possible rates of fire, but this will put limitations on possible homebrew unless custom rates can be entered by the GM.

**Comment by michalzc** [comment]
Probably there will be no automation. I will switch to text field.
